export default {
  Login: 'Login',
  welcomeToTinyAward: 'Welcome to Tiny Award',
  publicBadges: 'Public Badges',
  search: 'Search',
  redeemCode: 'Redeem code',
  issuer: 'Issuer: ',
  welcomeToThinkingCap: 'Welcome to Thinking Cap',
  simpleBadgeCompany: 'Simple badge for learning a little about the company',
  info: 'Info',
  getExtension: 'Get Extension',
  go: 'Go',
  hideDetails: 'Hide Details',
  showDetails: 'Show Details',
  CopyrightPatentPending: `©Copyright ${new Date().getFullYear()} Agile.Net Inc.®. Patent Pending`,
  privacyPolicy: 'Privacy Policy',
  summary: 'Summary',
  hi: 'Hi ,',
  expries: 'Expries:',
  earn: 'Earned On:',
  none: 'None',
  logout: 'Log Out',
  never: 'Never',
  criteria: 'Criteria:',
  Alignment: 'Alignments:',
  issuedBy: 'Issued by:',
  alignmentTitle: 'Alignments',
  read: 'Read',
  start: 'Start',
  readAndUnderStand: 'Read and understand',
  done: 'Done!',
  quiz: 'Quiz',
  percentage: '%',
  cancel: 'Cancel',
  details: 'Details',
  question: 'Question',
  login: 'Log in',
  of: 'of',
  submit: 'Submit',
  congratulations: 'Congratulations',
  youEarnedTinyAward: 'You’ve Earned a Tiny Award',
  viewPortfolio: 'View in Portfolio',
  isssuedBy: 'Issued By: ',
  viewInDashboard: 'View in Dashboard',
  signInGoogle: 'Sign in with Google',
  signInMicroSoft: 'Sign in with Microsoft',
  loginWithFaceBook: 'Log in With Facebook',
  loginWithAmazon: 'Login with Amazon',
  signInWithLinkedIn: 'Sign in with LinkedIn',
  noBadgesList: 'No Badges to List',
  allDone: 'All Done',
  shareYourAchievement: 'Share Your achievement!',
  passingScoreDescription: 'Sorry you did not achieve the passing score of ',
  yourScore: 'Your score is ',
  continue: 'Continue',
  tryAgain: 'Try Again',
  earned: 'Earned',
  finish: 'Finish',
};
