import {StyleSheet} from 'react-native';
import {getScaledFont, height, width} from '../../../global/fonts';
import {fonts} from '../../../assets';
import colors from '../../../global/colors';

export const styles = StyleSheet.create({
  safeWrapper: {
    flex: 1,
    backgroundColor: colors.headerBlue,
  },
  webView: {
    flex: 1,
    paddingHorizontal: getScaledFont(10),
    // backgroundColor:'red'
  },
  // progressWrapper: {
  //   top: height(123),
  //   borderRadius: getScaledFont(10),
  //   transform: [{rotate: '-90deg'}],
  // },
  emptyView: {
    height: height(3),
  },
  watchText: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
  },
  watchWrapper: {
    position: 'absolute',
    top: '55%',
    width: width(200),
    height: height(150),
    right: 0,
    borderTopStartRadius: getScaledFont(20),
    borderBottomStartRadius: getScaledFont(20),
    backgroundColor: colors.backGround,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loader: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backGround,
  },
  bottomContext: {
    position: 'absolute',
    width: '100%',
    bottom: getScaledFont(20),
    alignItems: 'center',
  },
  bottomBtn: {
    // height: height(60),
    paddingVertical: height(10),
    backgroundColor: colors.yellow,
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: getScaledFont(8),
  },
  buttonTxt: {
    fontSize: getScaledFont(30),
    fontFamily: fonts.bold,
    color: colors.black,
    textAlign: 'center',
  },
  topWrapper: {
    justifyContent: 'center',
  },
  headerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: height(84),
    width: '100%',
    paddingStart: width(36.5),
    paddingEnd: width(5),
    marginVertical: height(5),
    borderBottomStartRadius: getScaledFont(12),
    borderBottomEndRadius: getScaledFont(12),
    zIndex: 2,
    position: 'absolute',
  },
  scrollHeader: {
    position: 'absolute',
    width: width(84),
    height: height(350),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomStartRadius: getScaledFont(12),
    borderBottomEndRadius: getScaledFont(12),
    zIndex: 2,
    paddingVertical: height(10),
  },
  progressWrapper: {
    // transform: [{scaleX: -1}],
    borderBottomStartRadius: getScaledFont(16),
    borderBottomEndRadius: getScaledFont(16),
    backgroundColor: colors.scrollDisabled,
    borderWidth: 0,
    borderRadius: 0,
    borderColor: colors.scrollDisabled,
    paddingHorizontal: width(10),
    // paddingVertical: height(8),
  },
  scrollwrapper: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: height(350),
    width: width(84),
    borderBottomStartRadius: getScaledFont(12),
    borderBottomEndRadius: getScaledFont(12),
    zIndex: 2,
    backgroundColor: colors.headerBlue,
    borderRadius: getScaledFont(8),
    right: 0,
    top: height(200),
    paddingVertical: height(10),
  },
  leftWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: '15%',
    gap: -10,
  },
  scrollLeftWrapper: {
    alignItems: 'center',
  },
  percentageTxt: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.medium,
    color: colors.lightYellow,
    textAlign: 'center',
  },
  cancelText: {
    fontFamily: fonts.bold,
    color: colors.white,
    fontSize: getScaledFont(14),
    width: '100%',
    height: height(30),
    alignItems: 'center',
  },
  watchCancel: {
    fontFamily: fonts.bold,
    color: colors.yellow,
    fontSize: getScaledFont(20),
    width: '100%',
    paddingVertical: height(10),
    textAlign: 'center',
  },
  videoWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: height(10),
    marginBottom: height(15),
  },
});
