import {StyleSheet} from 'react-native';
import {getScaledFont, height, width} from '../../../global/fonts';
import {fonts} from '../../../assets';
import colors from '../../../global/colors';

export const styles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
  },
  safeWrapper: {
    flex: 1,
    backgroundColor: colors.linerBlueGradientOne,
  },
  topContainer: {
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'space-between',
  },
  scrollContainer: {
    height: '80%',
  },
  emptyWrapper: {
    marginTop: height(10),
  },
  alignmentWrapper: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginHorizontal: width(14),
  },
  headerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: height(61),
    marginHorizontal: width(32),
    marginTop: height(16),
    marginBottom: height(16),
  },
  listWrapper: {
    flexWrap: 'wrap',
    flexDirection: 'row',
    columnGap: 5,
    rowGap: 5,
    marginTop: height(20),
    marginHorizontal: width(14),
  },
  buttonContainer: {
    width: width(400),
    height: height(120),
  },
  tagWrapper: {
    paddingHorizontal: width(6),
    paddingVertical: height(6),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: getScaledFont(20),
    borderWidth: getScaledFont(1),
    backgroundColor: colors.grey,
  },
  alignWrapper: {
    paddingHorizontal: width(12),
    paddingVertical: height(6),
    marginVertical: height(1),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: getScaledFont(20),
    borderWidth: getScaledFont(1),
    backgroundColor: colors.blue,
  },
  bottomContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 10,
  },
  leftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '50%',
  },
  rightWrappper: {
    alignItems: 'flex-end',
    width: '50%',
    height: height(61),
  },
  readTxt: {
    fontSize: getScaledFont(30),
    color: colors.white,
    fontFamily: fonts.bold,
  },
  tagTxt: {
    fontSize: getScaledFont(18),
    color: colors.textWhite,
    fontFamily: fonts.bold,
  },
  alignTxt: {
    fontSize: getScaledFont(18),
    color: colors.textWhite,
    fontFamily: fonts.bold,
    textTransform: 'capitalize',
  },
  headerText: {
    fontSize: getScaledFont(18),
    fontFamily: fonts.medium,
    color: colors.white,
    marginStart: width(10),
  },
  logoWrapper: {
    height: height(61),
    width: width(45),
  },
  imageWrapper: {
    height: height(200),
    width: width(200),
    resizeMode: 'contain',
  },
  imageContainer: {
    marginTop: height(16),
    marginBottom: height(40),
    alignItems: 'center',
  },
  buttonTopWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  leftWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
  },
  headerRightWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  buttonWrapper: {
    marginHorizontal: width(14),
  },
  mainTitleTxt: {
    fontSize: getScaledFont(32),
    fontFamily: fonts.bold,
    color: colors.white,
    textAlign: 'center',
    marginTop: height(24),
    marginBottom: height(32),
    marginHorizontal: width(14),
  },
  divider: {
    width: '100%',
    borderWidth: 0.7,
    borderColor: colors.white,
  },
  pendingText: {
    fontSize: getScaledFont(16),
    fontFamily: fonts.medium,
    color: colors.darkYellow,
    textAlign: 'center',
  },
  privacyText: {
    fontSize: getScaledFont(16),
    fontFamily: fonts.medium,
    color: colors.darkYellow,
    textAlign: 'center',
    textDecorationStyle: 'solid',
    textDecorationLine: 'underline',
    textDecorationColor: colors.darkYellow,
    marginBottom: height(3),
  },
  titleTxt: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.semiBold,
    color: colors.white,
    marginBottom: height(16),
  },
  detailContanier: {
    marginStart: width(24),
  },
  detailBtnWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: height(16),
    marginBottom: height(18),
  },
  descriptionTxt: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.medium,
    color: colors.white,
    marginTop: height(16),
    marginHorizontal: width(14),
  },
  alignmentTxt: {
    fontSize: getScaledFont(24),
    fontFamily: fonts.bold,
    color: colors.white,
    marginTop: height(12),
    marginBottom: height(4),
    marginHorizontal: width(14),
  },
  detailsWrapper: {
    marginTop: height(48),
    marginBottom: height(28),
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBtn: {
    width: width(180),
    height: height(53),
    borderRadius: getScaledFont(8),
  },
  issueTxt: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.semiBold,
    fontStyle: 'italic',
    color: colors.white,
    marginHorizontal: width(14),
  },
  issueName: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.semiBold,
    color: colors.white,
    fontStyle: 'italic',
  },
  detailsTxt: {
    fontSize: getScaledFont(20),
    fontFamily: fonts.bold,
    color: colors.white,
  },
  topButton: {
    height: height(65),
    width: '100%',
    borderTopStartRadius: getScaledFont(8),
    borderTopEndRadius: getScaledFont(8),
    backgroundColor: colors.lightBtnBlue,
    justifyContent: 'center',
    paddingHorizontal: width(24),
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: colors.btnBorderColor,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  singleButton: {
    borderBottomWidth: 1,
    borderBottomEndRadius: getScaledFont(8),
    borderBottomStartRadius: getScaledFont(8),
  },
  bottomButton: {
    height: height(65),
    width: '100%',
    borderBottomStartRadius: getScaledFont(8),
    borderBottomEndRadius: getScaledFont(8),
    backgroundColor: colors.lightBtnYellow,
    paddingHorizontal: width(24),
    borderWidth: 1,
    borderTopWidth: 1,
    borderTopColor: colors.searchItemGray,
    borderColor: colors.btnBorderColor,
  },
  arrowWrapper: {
    position: 'absolute',
    marginStart: width(20),
    zIndex: 1,
    top: -3,
  },
  bottomButtonAlign: {
    height: height(65),
    justifyContent: 'center',
  },
});
